
# ------------------------------------------------------------
# English navigation
# ------------------------------------------------------------
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Faq"
url = "faq/"
weight = 2

[[main]]
name = "contact"
url = "contact/"
weight = 3

# Dropdown menu
[[main]]
weight = 4
name = "docs"
hasChildren = true

  [[main]]
  parent = "docs"
  name = "Sleep"
  url = "sleep/"
  weight = 1

  [[main]]
  parent = "docs"
  name = "Memory"
  url = "memory/"
  weight = 2

  [[main]]
  parent = "docs"
  name = "Dreaming"
  url = "dreaming/"
  weight = 3